spring:
    application:
        name: SpringbootVirtualThread
    threads:
        virtual:
            enabled: true
springdoc:
    swagger-ui:
        path: /swagger
        tryItOutEnabled: true
        displayRequestDuration: true